import { MD3LightTheme, MD3DarkTheme, configureFonts, MD3Theme } from 'react-native-paper';

const fontConfig = {
  displayLarge: { fontFamily: 'SpaceGrotesk', fontSize: 57, letterSpacing: 0, lineHeight: 64 },
  displayMedium: { fontFamily: 'SpaceGrotesk', fontSize: 45, letterSpacing: 0, lineHeight: 52 },
  displaySmall: { fontFamily: 'SpaceGrotesk', fontSize: 36, letterSpacing: 0, lineHeight: 44 },
  headlineLarge: { fontFamily: 'SpaceGrotesk', fontSize: 32, letterSpacing: 0, lineHeight: 40 },
  headlineMedium: { fontFamily: 'SpaceGrotesk', fontSize: 28, letterSpacing: 0, lineHeight: 36 },
  headlineSmall: { fontFamily: 'SpaceGrotesk', fontSize: 24, letterSpacing: 0, lineHeight: 32 },
  titleLarge: { fontFamily: 'SpaceGrotesk', fontSize: 22, letterSpacing: 0, lineHeight: 28 },
  titleMedium: { fontFamily: 'SpaceGrotesk', fontSize: 16, letterSpacing: 0.15, lineHeight: 24 },
  titleSmall: { fontFamily: 'SpaceGrotesk', fontSize: 14, letterSpacing: 0.1, lineHeight: 20 },
  labelLarge: { fontFamily: 'SpaceGrotesk', fontSize: 14, letterSpacing: 0.1, lineHeight: 20 },
  labelMedium: { fontFamily: 'SpaceGrotesk', fontSize: 12, letterSpacing: 0.5, lineHeight: 16 },
  labelSmall: { fontFamily: 'SpaceGrotesk', fontSize: 11, letterSpacing: 0.5, lineHeight: 16 },
  bodyLarge: { fontFamily: 'SpaceGrotesk', fontSize: 16, letterSpacing: 0.15, lineHeight: 24 },
  bodyMedium: { fontFamily: 'SpaceGrotesk', fontSize: 14, letterSpacing: 0.25, lineHeight: 20 },
  bodySmall: { fontFamily: 'SpaceGrotesk', fontSize: 12, letterSpacing: 0.4, lineHeight: 16 },
};

export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3LightTheme.colors,
    primary: '#202020',
    onPrimary: '#FFFFFF',
    primaryContainer: '#C9F158',
    onPrimaryContainer: '#202020',
    secondary: '#202020',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#F2F3F5',
    onSecondaryContainer: '#202020',
    tertiary: '#C9F158',
    onTertiary: '#202020',
    tertiaryContainer: '#C9F158',
    onTertiaryContainer: '#202020',
    error: '#FF4D4F',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#410002',
    background: '#F2F3F5',
    onBackground: '#202020',
    surface: '#FFFFFF',
    onSurface: '#202020',
    surfaceVariant: '#FFFFFF',
    onSurfaceVariant: '#7A7A7A',
    outline: '#EAEAEA',
    outlineVariant: '#EFEFEF',
    surfaceDisabled: '#F2F3F5',
    onSurfaceDisabled: '#7A7A7A',
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level1: '#FFFFFF',
      level2: '#FFFFFF',
      level3: '#FFFFFF',
      level4: '#FFFFFF',
      level5: '#FFFFFF',
    },
  },
  roundness: 3, // M3 base multiplier
};

export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#C9F158',
    onPrimary: '#202020',
    primaryContainer: '#C9F158',
    onPrimaryContainer: '#202020',
    secondary: '#C9F158',
    onSecondary: '#202020',
    secondaryContainer: '#202020',
    onSecondaryContainer: '#FFFFFF',
    tertiary: '#C9F158',
    onTertiary: '#202020',
    tertiaryContainer: '#202020',
    onTertiaryContainer: '#FFFFFF',
    error: '#FF5A5F',
    onError: '#FFFFFF',
    errorContainer: '#93000A',
    onErrorContainer: '#FFDAD6',
    background: '#111111',
    onBackground: '#FFFFFF',
    surface: '#1A1A1A',
    onSurface: '#FFFFFF',
    surfaceVariant: '#202020',
    onSurfaceVariant: '#A1A1A1',
    outline: '#2A2A2A',
    outlineVariant: '#303030',
    surfaceDisabled: '#111111',
    onSurfaceDisabled: '#A1A1A1',
    elevation: {
      ...MD3DarkTheme.colors.elevation,
      level1: '#1A1A1A',
      level2: '#1A1A1A',
      level3: '#1A1A1A',
      level4: '#1A1A1A',
      level5: '#1A1A1A',
    },
  },
  roundness: 3,
};
